name: CI

on:
  pull_request:

jobs:
  test-81:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom
      - name: Composer install
        run: composer install
      - name: Lint
        run: composer run lint
      - name: Test
        run: composer run test
