name: CI

on: pull_request

jobs:
  test-81:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        uses: ./.github/actions/ci
        env:
          PHP_VERSION: 8.1
  test-82:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        uses: ./.github/actions/ci
        env:
          PHP_VERSION: 8.2
  test-83:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        uses: ./.github/actions/ci
        env:
          PHP_VERSION: 8.3
  test-84:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        uses: ./.github/actions/ci
        env:
          PHP_VERSION: 8.4
